services:
    cobalt:
        image: ghcr.io/imputnet/cobalt:latest

        init: true
        read_only: true
        restart: unless-stopped
        container_name: cobalt

        ports:
            - 9000:9000/tcp

    cobalt-web:
      image: ghcr.io/imputnet/cobalt-web:latest
      restart: unless-stopped
      ports:
        - "9001:3000"