services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=5799
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent/config:/config
      - "${USERPROFILE}/Downloads:/downloads"
    ports:
      - 5799:5799
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
