services:
  dumbdo:
    image: dumbwareio/dumbdo:latest
    container_name: dumbdo
    restart: always
    ports:
      - 4002:3000
    volumes:
      - ./data:/app/data
    environment:
      - DUMBDO_PIN=1234
      - DUMBDO_SITE_TITLE=DumbDo
