services:
  tinyfilemanager:
    container_name: tinyfilemanager
    image: prasathmani/tinyfilemanager:master
    volumes:
      - ./data:/var/www/html/data
    ports:
      - 3003:80
    restart: always