services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - ./config:/config:rw
      - "${HOME}/Downloads:/output:rw"
    restart: always
