services:
  dumbterm:
    image: dumbwareio/dumbterm:latest
    container_name: dumbterm
    restart: always
    ports:
      - 4005:3000
    volumes:
      - ./config:/root/.config
      - ./data:/root/data
    environment:
      # Container timezone
      TZ: America/Toronto
      # The title shown in the web interface
      SITE_TITLE: DumbTerm
      # Recommended PIN protection (leave empty to disable)
      DUMBTERM_PIN: 1234
      # The base URL for the application
      BASE_URL: http://192.168.1.2:4005
      ENABLE_STARSHIP: true
      LOCKOUT_TIME: 15 # Minutes
      # Session duration in hours before requiring re-authentication
      MAX_SESSION_AGE: 24 # Hours
      # (OPTIONAL) - List of allowed origins for CORS
      # ALLOWED_ORIGINS: ${DUMBTERM_ALLOWED_ORIGINS:-http://localhost:3000}
