services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "14" #15 does not allow user to sign into Apple ID
      DISK_SIZE: "50G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8007:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: always
    stop_grace_period: 2m